### ISSUE TITLE
PFTFile ignored by scuff-scatter

### ISSUE THREAD

**Issue by jmllorens** [HomerReid/scuff-em#101]
I have recently cloned and installed a recent version of the software. Everything went fine. After running a simple Mie calculation I noticed that the program ignores the PFTFile option, it works however with the synonymous EMTPFTFile option. I don't know whether is a problem of the program or the doc, meaing PFTFILE is deprecated.

**Comment by HomerReid** [comment]
Fixed in 975a839ba5af437923b04a4cc0395a3305eec3ac. Thanks for the bug report!
