### ISSUE TITLE
SCUFFEM config error

### ISSUE THREAD

**Issue by amrit-poudel** [HomerReid/scuff-em#103]
I tried building the most recent version of SCUFFEM from source, but get the following error:

configure: creating ./config.status
config.status: error: cannot find input file: Makefile.in

Also, I get this warning, which does not make sense:
configure: WARNING: unrecognized options: --with-hdf5

Here is how I have successfully built this package from the source in the past, but it generates the above error when I try to build the latest version of scuffem (on 4 different clusters  that I have tried so far):

export CPPFLAGS and LDFLAGS to to point to HDF5_MPI include and lib folders

sh autogen.sh --prefix=/home/amritpoudel/HPC_LIB/SCUFFEM_MPI

./configure --prefix=/home/amritpoudel/HPC_LIB/SCUFFEM_MPI --with-hdf5=/home/amritpoudel/HPC_LIB/HDF5_MPI --with-blas=/home/amritpoudel/HPC_LIB/OPENBLAS/lib/libopenblas.so --with-lapack=/home/amritpoudel/HPC_LIB/OPENBLAS/lib/libopenblas.so "CC=mpicc" "CXX=mpic++" "F77=gfortran" --without-python

I understand that I am using parallel version of hdf5,  but this has worked fine in the past, so I hope this is not an issue now.

I have included a config.log file here:

https://github.com/amrit-poudel/Boundary_Integral_Method/blob/master/config.log

I'd appreciate if you could help me resolve this error. Thanks.

**Comment by HomerReid** [comment]
My mistake. Fixed in c478796e9d366975b7bc890c600413854caae540. Thanks for the bug report. I also corrected the missing factor of 1/c^2 you pointed out in the tutorial.

**Comment by amrit-poudel** [comment]
Thank you for fixing it so quickly. I am now able to install the library without any issue. Also, I did a test run of ldos, which I will comment on another thread. I will close this issue. Thanks!
