### ISSUE TITLE
Difficulties installing Scuff-em

### ISSUE THREAD

**Issue by Issachooi** [HomerReid/scuff-em#104]
Dear Homer Reid,

While I'm trying to install Scuff-em in Ubuntu, I face the following problem.

checking hdf5.h usability... no
checking hdf5.h presence... no
checking for hdf5.h... no
checking H5pubconf.h usability... no
checking H5pubconf.h presence... no
checking for H5pubconf.h... no
configure: error: couldn't find HDF5; configure --without-hdf5

I did fetch the packages using the following command,
% sudo apt-get install liblapack-dev libblas-dev libhdf5-serial-dev python-dev gmsh

and libhdf5-serial-dev is already the newest version. 

Could you please guide me on the installation? Appreciate your help very much.

Best Regards
Chee Quen

**Comment by HomerReid** [comment]
As the error message says, the installer can't find the `hdf5.h` file (and other files). If the hdf5 package is correctly installed on your system in the default configuration, those files should be in `/usr/include.` If they aren't, the hdf5 package isn't installed on your system in the usual way. 

If you have some sort of non-standard HDF5 installation in which the header files and binaries are in non-standard locations, you can specify those using the `--with-hdf5-includedir` and `--with-hdf5-libdir` options to `configure.`

Like the error message says, you can always just configure `--without-hdf5` if you want to run without hdf5 support.

**Comment by HomerReid** [comment]
Feel free to keep this issue alive by asking further questions. If you are satisfied, please close the issue.
