### ISSUE TITLE
Missing scanner.c

### ISSUE THREAD

**Issue by Issachooi** [HomerReid/scuff-em#105]
Dear Homer Reid,

Here is the subsequent problem that I face during the installation of Scuff-em.

hooi0004@hooi0004-HP-Z400-Workstation:~/scuff-em$ sudo make install
Making install in src
make[1]: Entering directory '/home/hooi0004/scuff-em/src'
Making install in libs
make[2]: Entering directory '/home/hooi0004/scuff-em/src/libs'
Making install in libhrutil
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
make[4]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include/scuff-em'
 /usr/bin/install -c -m 644 libhrutil.h '/usr/local/include/scuff-em'
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
Making install in libhmat
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhmat'
make  install-am
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhmat'
make[5]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhmat'
make[5]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include/scuff-em'
 /usr/bin/install -c -m 644 libhmat.h '/usr/local/include/scuff-em'
make[5]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhmat'
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhmat'
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhmat'
Making install in libSGJC
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs/libSGJC'
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libSGJC'
make[4]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include/scuff-em'
 /usr/bin/install -c -m 644 libSGJC.h '/usr/local/include/scuff-em'
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libSGJC'
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libSGJC'
Making install in libMDInterp
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs/libMDInterp'
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libMDInterp'
make[4]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include/scuff-em'
 /usr/bin/install -c -m 644 libMDInterp.h '/usr/local/include/scuff-em'
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libMDInterp'
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libMDInterp'
Making install in libMatProp
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs/libMatProp'
Making install in cmatheval
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libMatProp/cmatheval'
test -f scanner.c || /bin/bash ../../../../ylwrap scanner.l .c scanner.c -- /bin/bash /home/hooi0004/scuff-em/missing flex  
lex.yyscanner.c is unchanged
/bin/bash ../../../../libtool  --tag=CC   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../..   -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -g -O2 -fopenmp -pthread -g -O2 -MT scanner.lo -MD -MP -MF .deps/scanner.Tpo -c -o scanner.lo scanner.c
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../.. -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -g -O2 -fopenmp -pthread -g -O2 -MT scanner.lo -MD -MP -MF .deps/scanner.Tpo -c scanner.c  -fPIC -DPIC -o .libs/scanner.o
g++: error: scanner.c: No such file or directory
g++: fatal error: no input files
compilation terminated.
Makefile:508: recipe for target 'scanner.lo' failed
make[4]: *** [scanner.lo] Error 1
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libMatProp/cmatheval'
Makefile:521: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libMatProp'
Makefile:385: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/hooi0004/scuff-em/src/libs'
Makefile:382: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/hooi0004/scuff-em/src'
Makefile:432: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

I do appreciate your help. Thanks alot.

Best Regards
Chee Quen

**Comment by Issachooi** [comment]
When I use "make" instead of "sudo make install", the following appears:

hooi0004@hooi0004-HP-Z400-Workstation:~/scuff-em$ make
make  all-recursive
make[1]: Entering directory '/home/hooi0004/scuff-em'
Making all in src
make[2]: Entering directory '/home/hooi0004/scuff-em/src'
Making all in libs
make[3]: Entering directory '/home/hooi0004/scuff-em/src/libs'
Making all in libhrutil
make[4]: Entering directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../..  -I../../..  -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib  -g -O2 -fopenmp -pthread -MT libhrutil.lo -MD -MP -MF .deps/libhrutil.Tpo -c -o libhrutil.lo libhrutil.cc
rm: cannot remove '.libs/libhrutil.o': Permission denied
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../.. -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -g -O2 -fopenmp -pthread -MT libhrutil.lo -MD -MP -MF .deps/libhrutil.Tpo -c libhrutil.cc  -fPIC -DPIC -o .libs/libhrutil.o
Assembler messages:
Fatal error: can't create .libs/libhrutil.o: Permission denied
Makefile:473: recipe for target 'libhrutil.lo' failed
make[4]: *** [libhrutil.lo] Error 1
make[4]: Leaving directory '/home/hooi0004/scuff-em/src/libs/libhrutil'
Makefile:385: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/hooi0004/scuff-em/src/libs'
Makefile:382: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/hooi0004/scuff-em/src'
Makefile:432: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hooi0004/scuff-em'
Makefile:364: recipe for target 'all' failed
make: *** [all] Error 2
hooi0004@hooi0004-HP-Z400-Workstation:~/scuff-em$ 


Best Regards
Chee Quen

**Comment by HomerReid** [comment]
The `make` is failing because by default it attempts to install to system-wide directories for which you need root access.

To get around this, use the `--prefix` argument to `configure` to specify an installation directory to which you have write access. For example, try

````
% configure --prefix=${HOME}/scuff-em-installation
% make install
````

**Comment by Issachooi** [comment]
Dear Homer Reid,

I typed in this:
./configure --prefix=/home/hooi0004/scuff-em-installation --with-hdf5-libdir=/usr/lib/x86_64-linux-gnu/hdf5/serial/lib --with-hdf5-includedir=/usr/include/hdf5/serial/

followed by sudo make install

It then showed:
...
...
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/hooi0004/scuff-em/interactiveTests'
make[1]: Leaving directory '/home/hooi0004/scuff-em/interactiveTests'
Making install in m4
make[1]: Entering directory '/home/hooi0004/scuff-em/m4'
make[2]: Entering directory '/home/hooi0004/scuff-em/m4'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/hooi0004/scuff-em/m4'
make[1]: Leaving directory '/home/hooi0004/scuff-em/m4'
make[1]: Entering directory '/home/hooi0004/scuff-em'
make[2]: Entering directory '/home/hooi0004/scuff-em'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/hooi0004/scuff-em'
make[1]: Leaving directory '/home/hooi0004/scuff-em'

Does it imply that scuff-em is properly installed?

Best Regards
Chee Quen

**Comment by Issachooi** [comment]
Meanwhile, a scuff-em-installation folder is created in /home

**Comment by Issachooi** [comment]
And I tried to run the program by:

scuff-analyze --mesh RoundedBeamUnitCell_192.msh. It return:

scuff-analyze: command not found

Is scuff-em not properly installed?

**Comment by HomerReid** [comment]
> Does it imply that scuff-em is properly installed?

yes

> scuff-analyze: command not found

since you installed the code to `/home/hooi0004/scuff-em`, the executables are installed in `/home/hooi0004/scuff-em/bin, and there are two ways to communicate this information to the shell when running one of the executables:

````
% /home/hooi0004/scuff-em/bin/scuff-analyze --mesh RoundedBeamUnitCell_192.msh
````

````
% export PATH=${PATH}:/home/hooi0004/scuff-em/bin
% scuff-analyze --mesh RoundedBeamUnitCell_192.msh
````

**Comment by Issachooi** [comment]
Dear Homer Reid,

I appreciate your support and guidance so much, and I feel extremely thankful for your contribution in this field. 

I will be using scuff-em mainly for the evaluation of Casimir forces in graphene system.

Best Regards
Chee Quen

**Comment by HomerReid** [comment]
I'm glad it's working. If you are satisfied with the resolution of your questions, please close the issues.
