### ISSUE TITLE
.scuffgeo syntax

### ISSUE THREAD

**Issue by Issachooi** [HomerReid/scuff-em#107]
Dear Homer Reid,

In the Scuff-em documentation (geometry file examples), some SURFACE statements actually end with ENDOBJECT statements. I'm wondering why is that. 

For example the following:

**LATTICE 
    VECTOR 2.4 0.0 0.0 
    VECTOR 0.0 2.4 0.0
ENDLATTICE 

REGION UpperHalfSpace MATERIAL Vacuum
REGION LowerHalfSpace MATERIAL Silicon
REGION SphereInterior MATERIAL Gold

SURFACE Sphere
    MESHFILE Sphere.msh
    DISPLACED 1.2 1.2 1.85
    REGIONS UpperHalfSpace SphereInterior
ENDOBJECT

SURFACE Substrate
    MESHFILE Square.msh
    REGIONS UpperHalfSpace LowerHalfSpace
ENDOBJECT**

Appreciate your answer. Thanks

Best Regards
Chee Quen

**Comment by HomerReid** [comment]
Thanks for pointing this out. I have updated the documentation to fix this.

(The issue is actually harmless in practice because `ENDOBJECT` and `ENDSURFACE` are parsed as interchangeable keywords, but you're correct to point out that this makes for confusing documentation.)
