### ISSUE TITLE
Materials specified using tabulated data (complex numbers)

### ISSUE THREAD

**Issue by Issachooi** [HomerReid/scuff-em#108]
Dear Homer Reid,

In the case of specifying material's complex dielectric permittivity using a tabulated data, what should the format be? I created a material file as follow with guidance from scuff-em documentation which I named it **Graphene.txt**. The left column is frequency and the right one is the corresponding complex permittivity. 

--omega 31415926535897.9 --omega 7.89110029561670e-09+4.60324088238634e-10i
--omega 43887575763716.7 --omega 3.92318242035428e-09+2.42453092064446e-10i
--omega 56359224991535.5 --omega 2.28671540588520e-09+1.76576958809594e-10i
--omega 68830874219354.3 --omega 1.45988836737180e-09+1.51267208514149e-10i
--omega 81302523447173.1 --omega 9.86532806386208e-10+1.40634391127731e-10i
--omega 93774172674991.8 --omega 6.91678260952833e-10+1.36469884167432e-10i
--omega 106245821902811 --omega 4.96615226543037e-10+1.35577658526074e-10i

However, I got this error message when I try to run scuff-cas3D:

**error: no imaginary-frequency data given in material data file /home/hooi0004/scuff-em-installation/share/scuff-em/examples/Graphene.txt (aborting)**

Looking forward to your advice. Thank you so much.

Best Regards
Chee Quen

**Comment by Issachooi** [comment]
The entire **Graphene.txt** has 200 data entries. And it is generated from a Matlab code written to calculate the dielectric permittivity of graphene.

**Comment by HomerReid** [comment]
http://homerreid.github.io/scuff-em-documentation/reference/Materials/#Tabulated
