### ISSUE TITLE
How to compute scattering component of force/torque?

### ISSUE THREAD

**Issue by odmiller** [HomerReid/scuff-em#118]
Hi Homer,

It looks like in the "EMTPFT" approach you compute forces and torques by computing the "extinction" quantity and then subtracting the scattered-field component. What is the easiest way to actually get the scattered-field component (or of equal value the extinction component) by itself?

It looks like on lines 207-209 of GetPFT.cc you get the PFT Matrix and PFT values, with the key call being `HMatrix *PFTMatrix = GetEMTPFTMatrix(this, Omega, IF, KN, DRMatrix, 0, Interior, Method);`

Am I correct that if I simply nullify the incident field, i.e. make the call `HMatrix *PFTMatrix = GetEMTPFTMatrix(this, Omega, 0, KN, DRMatrix, 0, Interior, Method);` then I will get the (negative of the) scattered-field component? So that if I then simply follow up with `PFTMatrix->GetEntriesD(SurfaceIndex, ":", PFT);` the `PFT` matrix will contain the negative of the scattered-field components?

(By the way, what does this function compute if one chooses `Exterior` instead of `Interior`?)

**Comment by HomerReid** [comment]
> Am I correct that if I simply nullify the incident field, i.e. make the call `HMatrix *PFTMatrix = GetEMTPFTMatrix(this, Omega, 0, KN, DRMatrix, 0, Interior, Method);` then I will get the (negative of the) scattered-field component? So that if I then simply follow up with` PFTMatrix->GetEntriesD(SurfaceIndex, ":", PFT);` the PFT matrix will contain the negative of the scattered-field components?

Yes, you got it, except here `PFT

**Comment by odmiller** [comment]
Very helpful, and informative! Thanks
