### ISSUE TITLE
Simulating weak scatterers

### ISSUE THREAD

**Issue by davidkleiven** [HomerReid/scuff-em#121]
Hi,

I am interested in simulation weak scatterers with refractive index around n=0.99999. To test the code I am simulating scattering from a sphere and comparing with the Mie scattering results. However, it works fine for the cases n=0.999 and n=0.9999, but when I try with 0.99999 the results deviate much more from the exact solution. I have tried refining the mesh, but it does not seem to help much. Is there a limit on how small differences in refractive index scuff-em can handle? If so, where does it come from?

Thanks in advance.

**Comment by HomerReid** [comment]
I haven't ever considered objects with such weak dielectric contrast. If *n* differs from 1 by one part in 10^5, then \epsilon differs from 1 by one part in 10^10, so we are effectively wasting 10 out of the 15 digits available for storing numbers in standard 64-bit floating-point registers, and there are many places in which numerical inaccuracies could then arise.

You might try your calculations in my volume-integral solver, BUFF-EM, which works explicitly with the quantity \epsilon-1 and may yield better results for ultra-low index-contrast materials.

http://homerreid.github.io/buff-em-documentation

**Comment by davidkleiven** [comment]
Thanks for the answer, numerical precision was my first thought as well I just wanted to check if it could be due to something else. I will check out BUFF-EM. I will close the issue.

A tiny detail: I don't think the argument that epsilon differs from 1 by one part in 10^10 is correct. If n = 0.99999
and epsilon = n^2 = 0.99998 it differs from 1 by 2 parts in 10^5. Anyway, it does not change the answer.

**Comment by HomerReid** [comment]
You're right---my mistake.
