### ISSUE TITLE
IFFile option no longer supported in SCUFF-SCATTER

### ISSUE THREAD

**Issue by psv2** [HomerReid/scuff-em#127]
I tried to create an incident field file and use the "--IFFile" option to pass that as a list of separate right-hand sides for solving scattering problems, but it seems like SCUFF-SCATTER no longer recognizes that option (aborting and instead giving me the list of recognized options). Is this a bug/regression, or could this be an issue with the local installation? (I don't have the version of SCUFF-SCATTER readily available, but I'll add it as soon as I find out.)

**Comment by HomerReid** [comment]
No, there has been no change to this. `--IFFile` is supported in the current repository version of SCUFF-SCATTER.

**Comment by psv2** [comment]
It turns out that I was using a much older version of SCUFF-SCATTER (probably over 2 years old at this point), and having installed the latest version, I can now use the "--IFFile" option. I'll close this issue.
