### ISSUE TITLE
Scuff-EM on Windows

### ISSUE THREAD

**Issue by rfmichael** [HomerReid/scuff-em#133]
Has anyone a Windows binary of Scuff-EM? I'm especially interested in Scuff-RF.

I also tried to compile it by myself, but it seems to be impossible.
First of all, libRWG seems to be missing and nowhere available in the internet.
Furthermore, there are several issues in the code that does not work.
For example: RWGObject seems to be incompletely moved to RWGSurface.

Can anyone help?

**Comment by HomerReid** [comment]
What code base are you using? `libRWG` and `RWGObject` are archaic symbols from a much earlier incarnation of the code--probably more than 6 or 7 years old.

I'm not aware of any successful attempts to build SCUFF-EM on a Windows machine, but surely it wouldn't be hard for somebody knowledgeable in these things to get the build working with cygwin or mingwin or other suchlike tools.

Feel free to ask more questions, or close the issue if satisfied.

**Comment by rfmichael** [comment]
Thanks for the answer!
Uops, you are right. I use qmake and just took all files, but obviously there are files inside the branch that are not used anymore. Sorry to bother you. I should have had a look into Makefile.am.

For example in scuff-rf, the files GetMinDistanceToPanel.cc and PointInsideObject.cc seems to be obsolete.
The same seems to hold for SphericalMoments.cc in libscuff. I think they should be removed.
Maybe there are even more obsolete files. I have not looked into it deeper.

I will try again and let you know.
Thanks for Scuff-EM!

**Comment by rfmichael** [comment]
Scuff-EM compiles fines with MinGW (Windows64 version 4.8.2).
I had to adjust a few small things (perhaps because I built the config.h by myself), but now Scuff-RF works as expected.

**Comment by HomerReid** [comment]
Good to know! Feel free to ask more questions, or close the issue if satisfied.
