### ISSUE TITLE
out of memory error when running scuff-transmission with PFT_794.args

### ISSUE THREAD

**Issue by gevero** [HomerReid/scuff-em#14]
Whenever I run scuff-transmission with the Perforated Thin Film example input file PFT_794.args as follows:

`scuff-transmission < PFT_794.args`

After having computed the first 5 omegas I get the following error:

`error: out of memory (aborting)`

It happens with both gcc and icc, lapack and mkl. Of course the code in only taking about 5G of the available 128G. The other PFS examples, such as PFS_1491.args run without issues.

Best

Giovanni

**Comment by gevero** [comment]
Coming back to this issue after a long time. What I discovered is the following: The out of memory error is a function of the frequency: It does appear even for a computation of a single frequency, but only for high frequencies. The computation log is as follows:

```
10/07/15::17:38:39: scuff-transmission running on RK013240 
10/07/15::17:38:39: Adding lattice basis vector (0.75,0). 
10/07/15::17:38:39: Adding lattice basis vector (0,0.75). 
10/07/15::17:38:39:  Mem before straddlers: 100 
10/07/15::17:38:39:  Detected (20,20) straddlers for surface UnitCell 
10/07/15::17:38:39: Surface UnitCell: {Straddlers, ExteriorEdges}={40,40} {closed} 
10/07/15::17:38:39: Flipped 250 panel normals to comport with region definitions. 
10/07/15::17:38:39: Identified source region as region # 0 (EXTERIOR). 
10/07/15::17:38:39: Identified dest region as region   # 0 (EXTERIOR). 
10/07/15::17:38:39: Calculating at 1 incident angles in range Theta=(0.000000e+00,0.000000e+00) degrees 
10/07/15::17:38:39: Solving the scattering problem at (Omega,Theta)=(15.1262,0) 
10/07/15::17:38:39: Assembling BEM matrix block (0,0) 
10/07/15::17:38:39:  Step 1: Contributions of innermost grid cells... 
10/07/15::17:38:39:   ...(1,1) block... 
10/07/15::17:38:45:   ...(1,0) block... 
10/07/15::17:38:51:   ...(1,-1) block... 
10/07/15::17:38:57:   ...(0,1) block... 
10/07/15::17:39:03:   ...(0,0) block... 
10/07/15::17:39:10:  Step 2: Contributions of outer grid cells... 
10/07/15::17:39:10: Creating GBar accelerator for region EXTERIOR, surfaces UnitCell,UnitCell 
10/07/15::17:39:10: error: out of memory (aborting)
```

In this case I selected a single frequency (15.126186850617522) from OmegaFile.PFT. The error happens for all the other higher frequencies, but not for the ones on the lower end (5.983986006837702, 6.095627536816017, 6.211513991888564... and so on). I hope this helps to shed some light on the problem.

Best

**Comment by HomerReid** [comment]
I see. So, this is actually not a bug. As you can see from the last lines of the log file, the code is running out of memory when it tries to build an interpolation table for calculating the periodic Green's function. This function is more rapidly varying at higher frequencies, so the interpolation table needs to be more finely sampled and thus larger in memory.

However, I have reason to believe that the default settings for how the code chooses the fineness of the interpolation grid are too stringent (more accurate than necessary), so it should be possible to relax them significantly, thus reducing the size of the interpolation table so that it will fit in memory.

To do this, modify the environment variable `SCUFF_INTERPOLATION_TOLERANCE` from its default value of `1e-6` to something like `1e-3` and try again. I expect this will clear up the out-of-memory issue. Then you can play around with the value of the tolerance that is needed to achieve accuracy, but I believe `1e-3` should be more than enough.

**Comment by gevero** [comment]
Your suggestion works, the log is:

```
10/08/15::13:02:13: scuff-transmission running on RK013240 
10/08/15::13:02:13: Adding lattice basis vector (0.75,0). 
10/08/15::13:02:13: Adding lattice basis vector (0,0.75). 
10/08/15::13:02:13:  Mem before straddlers: 100 
10/08/15::13:02:13:  Detected (20,20) straddlers for surface UnitCell 
10/08/15::13:02:13: Surface UnitCell: {Straddlers, ExteriorEdges}={40,40} {closed} 
10/08/15::13:02:13: Flipped 250 panel normals to comport with region definitions. 
10/08/15::13:02:13: Identified source region as region # 0 (EXTERIOR). 
10/08/15::13:02:13: Identified dest region as region   # 0 (EXTERIOR). 
10/08/15::13:02:13: Calculating at 1 incident angles in range Theta=(0.000000e+00,0.000000e+00) degrees 
10/08/15::13:02:13: Solving the scattering problem at (Omega,Theta)=(20.944,0) 
10/08/15::13:02:13: Assembling BEM matrix block (0,0) 
10/08/15::13:02:13:  Step 1: Contributions of innermost grid cells... 
10/08/15::13:02:13:   ...(1,1) block... 
10/08/15::13:02:19:   ...(1,0) block... 
10/08/15::13:02:25:   ...(1,-1) block... 
10/08/15::13:02:30:   ...(0,1) block... 
10/08/15::13:02:36:   ...(0,0) block... 
10/08/15::13:02:43:  Step 2: Contributions of outer grid cells... 
10/08/15::13:02:43: Creating GBar accelerator for region EXTERIOR, surfaces UnitCell,UnitCell 
10/08/15::13:02:43: Setting interpolation tolerance to 1.000000e-03. 
10/08/15::13:02:43: Creating interpolation grid with (100x100x43)=430000 grid points... 
10/08/15::13:03:04: ...interpolation table constructed! 
10/08/15::13:03:04: Creating GBar accelerator for region UnitCell, surfaces UnitCell,UnitCell 
10/08/15::13:03:04: Skipping interpolation table for region 1 
10/08/15::13:03:31: Creating GBar accelerator for 17 points in region EXTERIOR... 
10/08/15::13:03:31: Setting interpolation tolerance to 1.000000e-03. 
10/08/15::13:03:31: Creating interpolation grid with (20x20x9)=3600 grid points... 
10/08/15::13:03:31: ...interpolation table constructed! 
10/08/15::13:03:31: Creating GBar accelerator for 17 points in region UnitCell... 
10/08/15::13:03:33: Creating GBar accelerator for 17 points in region EXTERIOR... 
10/08/15::13:03:33: Setting interpolation tolerance to 1.000000e-03. 
10/08/15::13:03:33: Creating interpolation grid with (29x29x13)=10933 grid points... 
10/08/15::13:03:34: ...interpolation table constructed! 
10/08/15::13:03:34: Creating GBar accelerator for 17 points in region UnitCell... 
10/08/15::13:03:35: Creating GBar accelerator for 17 points in region EXTERIOR... 
10/08/15::13:03:35: Setting interpolation tolerance to 1.000000e-03. 
10/08/15::13:03:36: Creating interpolation grid with (20x20x9)=3600 grid points... 
10/08/15::13:03:36: ...interpolation table constructed! 
10/08/15::13:03:36: Creating GBar accelerator for 17 points in region UnitCell... 
10/08/15::13:03:37: Creating GBar accelerator for 17 points in region EXTERIOR... 
10/08/15::13:03:37: Setting interpolation tolerance to 1.000000e-03. 
10/08/15::13:03:38: Creating interpolation grid with (29x29x13)=10933 grid points... 
10/08/15::13:03:38: ...interpolation table constructed! 
10/08/15::13:03:38: Creating GBar accelerator for 17 points in region UnitCell... 
PFT_794.log (END) 
```

Nevertheless I was wondering that is the meaning of the `out of memory` error. The machine has plenty of memory at that point: is the error related to the maximum amount of memory allocated in a single variable or what else?

Thanks a lot!!!

**Comment by HomerReid** [comment]
If you don't think the machine is actually running out of memory, try doing 

````
 % ulimit -v unlimited 
````

before your `scuff-transmission` run. In some cases the default is to prohibit users from running programs that allocate more than a certain amount of memory, and this setting may be used to override that.

Also, you can look at the log file to see how big the interpolation tables are. Look for the lines that say `creating interpolation table with NX x NY x NZ grid points`. The interpolation tables store 512 bytes for every grid point, so in the example quoted in your post post above the size in memory would be 10933 x 512 = 5.8 MB, which is very small, but for high frequencies with strict interpolation tolerances these numbers can get quite large.
