### ISSUE TITLE
describe anisotropic materials in scuff-em

### ISSUE THREAD

**Issue by 1LuLu** [HomerReid/scuff-em#140]
Hi,
Is it possible to use the matrix to describe anisotropic materials in scuff-em? If  possible, how to achieve it？ I now know how to describe isotropic material in .scuffgeo. 

best
thank you in advance.

**Comment by HomerReid** [comment]
No, the surface-integral formulation implemented by SCUFF-EM does not allow handling of anisotropic materials. However, anisotropic and continuously spatially varying materials are supported by my BUFF-EM volume-integral solver.

Feel free to ask more questions, or close the issue if satisfied.

**Comment by 1LuLu** [comment]
Thank you very much, I'll close the issue and try to use BUFF-EM.
