### ISSUE TITLE
wavenumber  “k”

### ISSUE THREAD

**Issue by Kevin035** [HomerReid/scuff-em#153]
Dear prof. Reid,
I was puzzled by the wavenumber.
If the KIndex equals TD_HIGHK_HELMHOLTZ in scuff-em/doc/docs/forDevelopers/SingularIntegrals/TestTaylorDuffy.cc line 19， then the Kparam's imaginary part must be infinite. Is there any realistic situation when the wavenumber "k" imaginary party is infinite?

**Comment by HomerReid** [comment]
Yes, this case is relevant for computations at finite frequencies in lossy media, in which case the wavenumber acquires a large imaginary part, corresponding to rapid spatial decay of the fields. This is discussed in Section VIII of [this paper](https://arxiv.org/pdf/1312.1703.pdf).

Feel free to ask more questions, or close the issue if satisfied.

**Comment by Kevin035** [comment]
Thank you for your reply.
I want to download the MATHEMATICA code of Fig.3 in [the paper](https://arxiv.org/pdf/1312.1703.pdf), but I can not open the [website](http://homerreid.dyndns.org/scuff-EM/SingularIntegrals).

**Comment by HomerReid** [comment]
Thanks for the bug report. This is now fixed:

http://homerreid.github.io/scuff-em-documentation/forDevelopers/SingularIntegrals/

Feel free to ask more questions, or close the issue if satisfied.

**Comment by Kevin035** [comment]
Thank you very much.
