### ISSUE TITLE
scuff-transmission: unable to reproduce ThinFilm example

### ISSUE THREAD

**Issue by UmrathSt** [HomerReid/scuff-em#160]
Dear Homer,
I am unable to reproduce the ThinFilm example and also had no luck in reproducing the DiffractionPatterns and PerforatedThinFilm examples. 
The transmission results don't look how they should. I am using scuff from your last commid: "overhauled spherical-moment calculation and scuff-tmatrix application…".

Best regards
Stefan

**Comment by HomerReid** [comment]
Thanks for the bug report. This is the same issue as #159. It affects calculations with periodic boundary conditions with multithreading enabled. Non-PBC geometries are not affected, and the issue should be eliminated by disabling multithreading, although then things may b slow. I am working on a fix, but unfortunately I am in Japan with almost no free time at the moment so it is going slowly. I hope to address it this weekend. 

Ultimately this is really a symptom of the longstanding failure to address #22, which would have caught the problem sooner. We really need simple unit tests with TravisCI automation. Any volunteers to help?

**Comment by HomerReid** [comment]
Fixed in 284b202. Please confirm and feel free to post further questions, or close the issue if resolved.

**Comment by UmrathSt** [comment]
Thank you for the fix. I can confirm that its working.
