### ISSUE TITLE
scuff-em install failure on ubuntu

### ISSUE THREAD

**Issue by sanj0212** [HomerReid/scuff-em#161]
I am installing scuff-em on ubuntu 16.04.
While configuring scuff-em.. I first got hdf5 related error.. i.e. hdf5 not found.  I solved that error after some search..
./configure CPPFLAGS="-I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial" LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial
this solved hdf5 related error//

next I run make command.. I got below failed error.  Kindly suggest how to solve this error.

libtool: link: ranlib .libs/libscuff.a
libtool: link: rm -fr .libs/libscuff.lax
libtool: link: ( cd ".libs" && rm -f "libscuff.la" && ln -s "../libscuff.la" "libscuff.la" )
make[4]: Leaving directory '/home/apps/scuff-em/src/libs/libscuff'
Making all in python
make[4]: Entering directory '/home/apps/scuff-em/src/libs/python'
make[4]: *** No rule to make target 'scuff-python.cpp', needed by 'all'.  Stop.
make[4]: Leaving directory '/home/apps/scuff-em/src/libs/python'
Makefile:382: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/apps/scuff-em/src/libs'
Makefile:377: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/apps/scuff-em/src'
Makefile:427: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/apps/scuff-em'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by HomerReid** [comment]
You need the [SWIG](http://www.swig.org) package to build the python interface from source. (On a Debian/Ubuntu system you should be able to install it by saying `sudo apt-get install swig`). 

Alternatively, you can configure `--without-python` to bypass compilation of the python interface.

Regarding the HDF5 issue you reported, what you did is correct, and I added some comments to the [installation documentation](http://homerreid.github.io/scuff-em-documentation/reference/Installing/) that will hopefully clarify the situation. (Minor note: You don't need the `-L...` portion in your `CPPFLAGS`, only in your `LDFLAGS`, but this is harmless.)

Feel free to ask more questions, or close the issue if resolved.

**Comment by sanj0212** [comment]
Thanks for the input.
SWIG is already there in my system (SWIG 3.0.8).  So the error should not come.
I could install scuff-em --without-python successfully .  But python interface is very useful. Kindly suggest how can I resolve SWIG issue and make it work with python interface. I am using python 2.7

**Comment by HomerReid** [comment]
What happens if you add the `--enable-maintainer-mode` option to `configure`?

**Comment by sanj0212** [comment]
Thanks a lot.. issue is resolved.  I didn't get error message.

**Comment by HomerReid** [comment]
The first time you build in a new source tree, you should run `sh autogen [options]` instead of `configure [options].` This will have the same effect as running `configure --enable-maintainer-mode` later.

This is actually documented on the installation page:

http://homerreid.github.io/scuff-em-documentation/reference/Installing/

but I realize that these things can be confusing.

Feel free to ask further questions, or close the issue if resolved.
