### ISSUE TITLE
Apparently divergent field distribution from scuff-spectrum

### ISSUE THREAD

**Issue by acmcclung** [HomerReid/scuff-em#163]
I'm trying to use scuff-spectrum roughly following [this guide](http://homerreid.github.io/scuff-em-documentation/applications/scuff-spectrum/scuff-spectrum/#scuff-spectrum-calculation). I get the same mode frequency as in the example, but when I plot the field, I get an apparently divergent distribution, which seems unphysical. Is this the correct behavior?

``
scuff-spectrum --geometry sphere.scuffgeo --omega0 1.1-0.63i --Rx 0.2 --Ry 0.2 --N 14 --L 5 --EPFile evalpts
``

![field](https://user-images.githubusercontent.com/28812954/35463320-09f5c400-02be-11e8-888e-89952f3548b7.png)

[sphere.scuffgeo](https://github.com/HomerReid/scuff-em/files/1669398/sphere.scuffgeo.txt)
[Sphere.msh](https://github.com/HomerReid/scuff-em/files/1669400/Sphere.msh.txt)
[evalpts](https://github.com/HomerReid/scuff-em/files/1669387/evalpts.txt)
[sphere.ModeFrequencies](https://github.com/HomerReid/scuff-em/files/1669393/sphere.ModeFrequencies.txt)
[sphere_C0_w1.1+-0.63i_RX0.2_RY0.2_N15_Mode0.evalpts.ModeFields](https://github.com/HomerReid/scuff-em/files/1669396/sphere_C0_w1.1.-0.63i_RX0.2_RY0.2_N15_Mode0.evalpts.ModeFields.txt)
[plot_fields.py](https://github.com/HomerReid/scuff-em/files/1674012/plot_fields.py.txt)

**Comment by HomerReid** [comment]
This seems correct to me---if \omega has a negative imaginary part, then so does the free-space wavevector k, so the Green's function describing the fields of sources scales like e^{ikr}/r which blows up exponentially for large distances. It's complementary to what we do in Casimir physics, where we Wick-rotate the contours of frequency integrations so that omega develops a positive imaginary part, in which case the Green's function is exponentially *decaying* at large distances.

**Comment by acmcclung** [comment]
Ok, thank you for clarifying. I guess I expected the example to look for localized modes, which is ultimately what I am interested in. Also, the way quality factor is signed in [`havminv`](http://meep.readthedocs.io/en/latest/Python_User_Interface/#harminv) seems to expect resonant localized modes to have negative frequency, perhaps contributing to my confusion. In any case, I will set my contours to search Im(\omega) > 0.

**Comment by HomerReid** [comment]
Thanks for chiming in @jfeist! That looks like a very useful and recent reference. 

@acmcclung, just to reiterate what Johannes said, the frequency contours you were using before were fine as is---you don't want to look for eigenfrequencies in the upper half-plane. Also, this example *is* finding localized modes, and you should have no trouble plotting field profiles in and near the sphere---the subtlety involving exponential blowup at large distances doesn't preclude using the tool to study the frequencies and spatial profiles of cavity modes, although if you need to *normalize* the fields you may need to introduce some of the more complicated tools described in the paper Johannes cited.
