### ISSUE TITLE
I'm making a GPU version of scuff-em. Thoughts?

### ISSUE THREAD

**Issue by MyGithubNotYours** [HomerReid/scuff-em#164]
Hello Homer Reid

Thanks for this Scuff-em suite! I'm about halfway through converting the scuff-em suite to use GPUs instead of the CPU. Before I finish the remaining work, I figured I should ask:

1) Have you already made a GPU version (thus no need for me to do it)?
2) Or is there a technical reason why you haven't made a GPU version?

**Comment by HomerReid** [comment]
No, I have never tried this, but I'm not aware of a technical reason it shouldn't work. In fact the matrix-assembly step is embarrassingly parallel and should be amenable to GPU speedup. However, the system for caching and re-using the frequency-independent contributions to panel integrals involves global (geometry-wide) hash tables, so for massively parallel execution it might be faster to disable caching and recompute on the fly. Alternatively, if the caching happens in a GPU-local way then there may be no speed penalty. 

Feel free to continue the discussion, or close the issue if satisfied.
