### ISSUE TITLE
gmsh Physical Volume via cmd

### ISSUE THREAD

**Issue by Felixcb** [HomerReid/scuff-em#166]
Hi all,

I import a step-file to gmsh and want to mesh the part as a physical volume. I try it with the string command but it doesn't work. Following the code. I think in the quotes should be the command for the physical volume. 

`gmsh Desktop\part.stp -string "Physical Volume" -3 -o Desktop\part.inp`

I appreciate your help.
Regards
Felix

**Comment by HomerReid** [comment]
This is a question about [gmsh](gmsh.info), not SCUFF-EM. I encourage you to consult the 
[gmsh development site](https://gitlab.onelab.info/gmsh/gmsh) or address your question to the [gmsh mailing list](http://onelab.info/mailman/listinfo/gmsh/).
