### ISSUE TITLE
http://homerreid.dyndns.org is not accessible recently

### ISSUE THREAD

**Issue by chenxinxian** [HomerReid/scuff-em#168]
Hi 

I wonder if you can provide a new libscuff API access?

Thanks,

Xin

**Comment by chenxinxian** [comment]
Dear Homer Reid,

We need some kind guidance for the C++ interface. I wonder if you could point me to somewhere.

I would very much appreciate it.

Thanks,

Xin

**Comment by HomerReid** [comment]
My personal website was down briefly, but is back up now.

**Comment by CCherqui** [comment]
Is the website with the old documentation ever going back up?

Thanks,
Charles
