### ISSUE TITLE
Compilation on Mac OSX 10.9

### ISSUE THREAD

**Issue by nkurinsky** [HomerReid/scuff-em#20]
I get the following error when trying to compile with the configure command
./configure --prefix=/usr/local/scuff-em --without-hdf5 --without-openmp --with-pthreads

Geometry.cc  -fno-common -DPIC -o .libs/RWGGeometry.o
RWGGeometry.cc:250:6: error: use of undeclared identifier 'feenableexcept'; did
      you mean 'feraiseexcept'?
   { feenableexcept(FE_INVALID | FE_OVERFLOW);
     ^~~~~~~~~~~~~~
     feraiseexcept
/usr/include/fenv.h:235:12: note: 'feraiseexcept' declared here
extern int feraiseexcept(int /* excepts */);
           ^
1 error generated.
make[4]: *** [RWGGeometry.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by nkurinsky** [comment]
Note: I'm using the provided tag 0.95, not the current Github code

**Comment by jfeist** [comment]
This was fixed in #1 - you might want to consider switching to the Github master branch. I've found that that is usually stable and you gain more by having the latest bugfixes than you lose by having some in-development code. 
However, you could also easily backport that fix (it's just a few lines) into the 0.95 version.

**Comment by nkurinsky** [comment]
Using the master branch is more complicated because (basically) I am too lazy to install glibtoolize, which seems to be necessary to run automake properly, but porting those lines from the other issue solved that problem. For the sake of other mac users, here's the info from my install; this was done on a fairly new macbook pro running OSX 10.9 without much more installed than autoconf and a few other GNU packages (such as GSL, which has BLAS).

- Get GFortran - http://hpc.sourceforge.net/
- Fix aforementioned issue in RWGGeometry.cc and scuff-test-Ewald.cc
- If using clang, the tr1/unordered_map can be changed to just unordered_map FIPPICache.cc, and the std::tr1 should be changed to std::
- I used ./configure --prefix=/path/to/installation --without-hdf5 --without-openmp --with-pthreads given a standard clean mac system with clang++

**Comment by HomerReid** [comment]
Thanks for this discussion, and I'm sorry I was traveling for the past several weeks and unable to respond. 

The 0.95 tarball on the scuff-em website seems to have created more problems than it solved, so I've taken that down. Hopefully any issues associated with building from GitHub on various systems will be worked out in short order once I have set up the TravisCI build-and-test framework. I will close this issue for now and create a new issue for that.
