### ISSUE TITLE
scuff-microstrip

### ISSUE THREAD

**Issue by eskiyerli** [HomerReid/scuff-em#224]
scuff-microstrip application is not being built as its makefile is not created by autogen.sh script. Is there a reason for that? Some examples still refer to it.

**Comment by cweickhmann** [comment]
I came across the same issue. From the commits it seems the project is not actively maintained at the moment.
@eskiyerli, have you come across a solution?

**Comment by eskiyerli** [comment]
No abandoned It long time ago.

**Comment by cweickhmann** [comment]
Pity.
