### ISSUE TITLE
Simulation of 3D transmission lines in scuff-rf

### ISSUE THREAD

**Issue by eskiyerli** [HomerReid/scuff-em#226]
Is it possible to simulate 3D transmission lines , i.e. transmission lines with a thickness that is a significant fraction of problem geometry, in scuff-rf? I tried different ways to mesh such a structure, i.e. 2D, 3D and 2D meshing of a empty shell without its end caps. I also tried 1D (line) and 2D (surface) ports in python interface without success. Is it at all possible or am I just making a mistake in defining the ports?

**Comment by Walshaikhli** [comment]
Murat did you ever get the ports to work?

**Comment by eskiyerli** [comment]
I gave up on this long time ago.
