### ISSUE TITLE
scuff-tmatrix crashes when running on geometries described using REGIONS and SURFACES

### ISSUE THREAD

**Issue by ETomlinson** [HomerReid/scuff-em#28]

**Comment by HomerReid** [comment]
Fixed in 8ff57e054dc999527210e67d916f8be4191c7178. 

The GetSphericalMoments() routine was not properly checking for the existence of half-RWG basis functions, which are present only in cases involving REGIONS and SURFACES. This should be fixed now. Please verify and close the issue if satisfied.
