### ISSUE TITLE
Adaptive integration features: periodic equilibrium code

### ISSUE THREAD

**Issue by miflynn** [HomerReid/scuff-em#32]
Previous versions of scuff  have included case-by-case checking for integrand convergence so that oversampling of kBloch points can be reduced for transformations which have converged for a particular frequency. This feature seems to have been taken out, but it would significantly reduce computation time for periodic equilibrium calculations if it could be re-introduced.

**Comment by HomerReid** [comment]
Actually this feature hasn't been taken out, and as far as I can tell it is working correctly. Please double-check and let me know if you can identify any examples on which it is misbehaving.
