### ISSUE TITLE
Compute volume of objects described by REGIONS and SURFACES

### ISSUE THREAD

**Issue by ETomlinson** [HomerReid/scuff-em#35]
It would be very helpful if scuff-analyze had the added functionality to compute the volume of each REGION specified in a .scuffgeo file.

**Comment by HomerReid** [comment]
Fixed in 4a22f440b7ca3d8c95260e6599197b0cbf015f04. Use the new --RegionVolumes option to scuff-analyze. Please verify and close the issue if satisfied.

**Comment by ETomlinson** [comment]
Confirmed using the object below. Works like a charm. Thanks!
![screen shot 2015-03-27 at 9 33 00 pm](https://cloud.githubusercontent.com/assets/7970327/6879359/493e77b8-d4c9-11e4-986f-36f67fa23515.png)
