### ISSUE TITLE
libhmat suggestion: dot product between vectors

### ISSUE THREAD

**Issue by eunnieverse** [HomerReid/scuff-em#45]
The following operations for HVector datatype will be useful.  

dot product between vectors
complex conjugate for all elements

**Comment by HomerReid** [comment]
In 5fd499bdae3bd232e16ef54f27bf198ff87a8b11 there are some new routines:

````
cdouble HVector::Dot(HVector *B);   /* hermitian dot product, this \cdot B */
cdouble HVector::DotU(HVector *B);  /* non-conjugated dot product */
double  HVector::DotD(HVector *B);  /* real part of Dot()       */
````

Also, `HMatrix` has a matrix-vector multiplication method:

````
   /* matrix-vector multiplication, this*X = Y (xgemv))      */
   /* Trans='C' or 'T' for hermitian / non-hermitian adjoint */
   void HMatrix::Apply(HVector *X, HVector *Y, char Trans=0);
````

(All of these routines are just wrappers around the level-1 and level-2 BLAS). Please let me know how they work.

**Comment by eunnieverse** [comment]
Thanks Homer, I will let you know.
Eunnie
