### ISSUE TITLE
PlotPFTFlux in scuff-scatter displays zero for Torque_z

### ISSUE THREAD

**Issue by eunnieverse** [HomerReid/scuff-em#46]
I am running scuff-scatter with the option --PlotPFTFlux. The following are returned: 

Pabs
Pscat
Fx
Fy
Fz
Tx
Ty
Tz

Currently the .pp file returns zero for Tz, and nonzero for Pscat while Pscat should be zero instead. 
Thank you.

**Comment by HomerReid** [comment]
Thanks for the bug report. This should be fixed in 624a6d00bcdfdbd8565632aa8ef786335e4202c6. Please confirm and close the issue if OK.

**Comment by eunnieverse** [comment]
I have confirmed the fix. Thank you very much!
