### ISSUE TITLE
'RenameMesh, scuff-analyze, scuff-neq' can not be found.

### ISSUE THREAD

**Issue by ZhihaoJia16** [HomerReid/scuff-em#71]
I do commands in example "Thermal radiation, heat transfer, and non-equilibrium Casimir forces between silicon dioxide spheres"
% gmsh -2 -clscale 1 Sphere.geo
% RenameMesh Sphere.msh
% gmsh Sphere_501.msh
% scuff-analyze --geometry SiO2Spheres_1479.scuffgeo --WriteGMSHFiles
% gmsh SiO2Spheres_1479.pp
% scuff-neq --geometry SiO2Sphere_501.scuffgeo --OmegaFile --PRad

And get those:
jzh@jzh-virtual-machine:~$ cd '/home/jzh/scuff-em-installation/share/scuff-em/examples/SiO2Spheres' 
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ gmsh -2 -clscale 1 Sphere.geo
Info    : Running 'gmsh -2 -clscale 1 Sphere.geo' [Gmsh 2.8.3, 1 node, max. 2 threads]
Info    : Started on Sun Jan 24 21:53:29 2016
Info    : Reading 'Sphere.geo'...
Info    : Done reading 'Sphere.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Circle)
Info    : Meshing curve 2 (Circle)
Info    : Meshing curve 3 (Circle)
Info    : Meshing curve 4 (Circle)
Info    : Meshing curve 5 (Circle)
Info    : Meshing curve 6 (Circle)
Info    : Meshing curve 7 (Circle)
Info    : Meshing curve 8 (Circle)
Info    : Meshing curve 9 (Circle)
Info    : Meshing curve 10 (Circle)
Info    : Meshing curve 11 (Circle)
Info    : Meshing curve 12 (Circle)
Info    : Done meshing 1D (0.008 s)
Info    : Meshing 2D...
Info    : Meshing surface 14 (Ruled surface, MeshAdapt)
Info    : Meshing surface 16 (Ruled surface, MeshAdapt)
Info    : Meshing surface 18 (Ruled surface, MeshAdapt)
Info    : Meshing surface 20 (Ruled surface, MeshAdapt)
Info    : Meshing surface 22 (Ruled surface, MeshAdapt)
Info    : Meshing surface 24 (Ruled surface, MeshAdapt)
Info    : Meshing surface 26 (Ruled surface, MeshAdapt)
Info    : Meshing surface 28 (Ruled surface, MeshAdapt)
Info    : Done meshing 2D (0.262425 s)
Info    : 170 vertices 401 elements
Info    : Writing 'Sphere.msh'...
Info    : Done writing 'Sphere.msh'
Info    : Stopped on Sun Jan 24 21:53:30 2016
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ RenameMesh Sphere.msh
RenameMesh: command not found
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ gmsh Sphere_501.msh
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ scuff-analyze --geometry SiO2Spheres_1479.scuffgeo --WriteGMSHFiles
scuff-analyze: command not found
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ gmsh SiO2Spheres_1479.pp
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ scuff-neq --geometry SiO2Sphere_501.scuffgeo --OmegaFile --PRad
scuff-neq: command not found

Here, 'RenameMesh, scuff-analyze, scuff-neq' can not be found. But I can find ‘scuff-analyze, scuff-neq' in directory of '/home/jzh/scuff-em-installation/bin'. I can visualize Sphere in 'Sphere_501.msh', but it is blank in 'SiO2Spheres_1479.pp'. Then I do 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/jzh/scuff-em-installation/lib/' and 'scuff-analyze'.
But 'scuff-analyze' can not be found yet:

jzh@jzh-virtual-machine:~$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/jzh/scuff-em-installation/lib/
jzh@jzh-virtual-machine:~$ scuff-analyze
scuff-analyze: command not found

Please give me  answer. 
Thank you.

**Comment by gevero** [comment]
Hi

- `RenameMesh`: you must download the `RenameMesh` script to the example folder from [here](http://homerreid.github.io/scuff-em-documentation/examples/SiO2Spheres/RenameMesh) and make it executable with `chmod +x RenameMesh`
- please check the content of the `'/home/jzh/scuff-em-installation/bin` folder. If the executables are indeed there you have two options: add the folder to your path adding the `PATH=$PATH:$HOME/scuff-em-installation/bin` to your `.bash_profile` and then source it or call the executable with the full path. Of course check that the files are executable in the first place.

best

**Comment by ZhihaoJia16** [comment]
Hi,
* I download the `RenameMesh` script to the example folder and run `chmod +x RenameMesh`. It doesn't work. Then I move `RenameMesh` script to folder in derectory of `/home/jzh/RenameMesh`, and run  `export PATH=$PATH:/home/jzh/RenameMesh`. It works.
* I add `PATH=$PATH:$HOME/scuff-em-installation/bin` line to `.profile` because I can not find `.bash_profile` in `/home` directory. And it works.

But I run `scuff-neq --geometry SiO2Sphere_501.scuffgeo --OmegaFile OmegaFile --PRad`, PRad flux spectral density is -0.00000000e+00.
```
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ scuff-neq --geometry SiO2Sphere_501.scuffgeo --OmegaFile OmegaFile --PRad
```
Here, I have download `OmegaFile` to directory of `/home/jzh/scuff-em-installation/share/scuff-em/examples/SiO2Spheres`. I open `SiO2Sphere_501.SIFlux.EMT`, it shows:
```
# scuff-neq run on jzh-virtual-machine (01/26/16::20:58:22)
# data file columns: 
# 1 transform tag
# 2 omega 
# 3 (sourceObject,destObject) 
# 4 PAbs flux spectral density
# 5 PRad flux spectral density
# 6 XForce flux spectral density
# 7 YForce flux spectral density
# 8 ZForce flux spectral density
# 9 XTorque flux spectral density
# 10 YTorque flux spectral density
# 11 ZTorque flux spectral density
DEFAULT 1.000000e-02 11 -3.46007296e-10 -0.00000000e+00 +6.17192225e-20 +1.57668250e-19 -2.39576813e-19 -2.94840323e-20 -2.79871230e-19 -9.01134754e-19 
DEFAULT 1.258925e-02 11 -8.70052178e-10 -0.00000000e+00 +2.46147196e-19 +6.28109102e-19 -9.54914714e-19 -1.54761314e-19 -7.10585720e-19 -2.30886853e-18 
DEFAULT 1.584893e-02 11 -2.18915585e-09 -0.00000000e+00 +9.83157854e-19 +2.50336244e-18 -3.80615465e-18 -3.78290523e-19 -1.71398060e-18 -5.91067938e-18 
DEFAULT 1.995262e-02 11 -5.51362174e-09 -0.00000000e+00 +3.92734176e-18 +9.98796916e-18 -1.51807329e-17 -1.04858086e-18 -4.20691821e-18 -1.48252077e-17 
DEFAULT 2.511886e-02 11 -1.39084962e-08 -0.00000000e+00 +1.57092930e-17 +3.98912460e-17 -6.06249664e-17 -2.79429045e-18 -1.04823195e-17 -3.73420184e-17 
DEFAULT 3.162278e-02 11 -3.51732779e-08 -0.00000000e+00 +6.30108775e-17 +1.59686479e-16 -2.42657803e-16 -7.79689191e-18 -2.55078915e-17 -9.45605983e-17 
DEFAULT 3.981072e-02 11 -8.93073695e-08 -0.00000000e+00 +2.53875466e-16 +6.41830647e-16 -9.74810123e-16 -2.26910395e-17 -6.07700233e-17 -2.40007828e-16 
DEFAULT 5.011872e-02 11 -2.28226067e-07 -0.00000000e+00 +1.02995632e-15 +2.59607977e-15 -3.94028405e-15 -6.95774989e-17 -1.39899983e-16 -6.13624456e-16 
DEFAULT 6.309573e-02 11 -5.89380994e-07 -0.00000000e+00 +4.22438690e-15 +1.06107064e-14 -1.60911581e-14 -2.24438159e-16 -2.97724130e-16 -1.58717915e-15 
DEFAULT 7.943282e-02 11 -1.54856357e-06 -0.00000000e+00 +1.76428408e-14 +4.41390625e-14 -6.68616207e-14 -7.71893596e-16 -5.21180415e-16 -4.18303536e-15 
DEFAULT 1.000000e-01 11 -4.18913321e-06 -0.00000000e+00 +7.59667464e-14 +1.89225711e-13 -2.86156245e-13 -2.83334015e-15 -3.05668448e-16 -1.13905528e-14 
DEFAULT 1.258925e-01 11 -1.19279347e-05 -0.00000000e+00 +3.45049823e-13 +8.55605348e-13 -1.29069204e-12 -1.13047574e-14 +4.03598517e-15 -3.28663608e-14 
DEFAULT 1.584893e-01 11 -3.74022845e-05 -0.00000000e+00 +1.73213102e-12 +4.27715364e-12 -6.42713970e-12 -5.07295978e-14 +3.70010490e-14 -1.05206021e-13 
DEFAULT 1.995262e-01 11 -1.44194361e-04 -0.00000000e+00 +1.07617389e-11 +2.64893786e-11 -3.95500685e-11 -2.85482059e-13 +2.94191982e-13 -4.16123040e-13 
DEFAULT 2.511886e-01 11 -1.00029556e-03 -0.00000000e+00 +1.22440653e-10 +3.02492405e-10 -4.46897543e-10 -2.92129234e-12 +3.89502845e-12 -3.00334768e-12 
DEFAULT 3.162278e-01 11 -2.78017328e-02 -0.00000000e+00 +5.84338096e-09 +1.41485646e-08 -2.03404229e-08 -7.58556101e-11 -2.45011491e-11 -6.64678197e-10 
DEFAULT 3.981072e-01 11 -2.29189547e-03 -0.00000000e+00 +6.55611387e-10 +1.59262462e-09 -2.44422193e-09 -1.33939905e-11 +1.51359562e-11 -2.35944164e-11 
DEFAULT 5.011872e-01 11 -1.64417225e-02 -0.00000000e+00 +7.98823921e-09 +1.94737800e-08 -2.87657106e-08 -1.73334242e-10 +2.25269100e-10 -1.64352198e-10 
DEFAULT 6.309573e-01 11 -3.10049683e-02 -0.00000000e+00 +2.60100680e-08 +6.91400747e-08 -9.88083203e-08 -6.29874293e-10 +8.13651824e-10 -3.53439933e-10 
DEFAULT 7.943282e-01 11 -5.40912166e-02 -0.00000000e+00 +5.82627840e-08 +1.40707711e-07 -2.08593903e-07 -5.53609968e-10 +7.28878802e-10 -2.91048815e-09 
```
PRad flux spectral density is -0.00000000e+00. Obviously, it is wrong compared with plot about power radiation (http://homerreid.github.io/scuff-em-documentation/examples/SiO2Spheres/SiO2Spheres/) 

When I run `scuff-neq --geometry SiO2Sphere_501.scuffgeo --Omega 1.0 --PRad` and `scuff-neq --geometry SiO2Sphere_501.scuffgeo --Omega 0.1 --PRad` for a single frequency, I get those:
```
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ scuff-neq --geometry SiO2Sphere_501.scuffgeo --Omega 1.0 --PRad
Thank you for your support.
jzh@jzh-virtual-machine:~/scuff-em-installation/share/scuff-em/examples/SiO2Spheres$ scuff-neq --geometry SiO2Sphere_501.scuffgeo --Omega 0.1 --PRad
Thank you for your support.
```
Then I open `SiO2Sphere_501.SIFlux.EMT`, it shows:
```
# scuff-neq run on jzh-virtual-machine (01/26/16::19:22:15)
# data file columns: 
# 1 transform tag
# 2 omega 
# 3 (sourceObject,destObject) 
# 4 PAbs flux spectral density
# 5 PRad flux spectral density
# 6 XForce flux spectral density
# 7 YForce flux spectral density
# 8 ZForce flux spectral density
# 9 XTorque flux spectral density
# 10 YTorque flux spectral density
# 11 ZTorque flux spectral density
DEFAULT 1.000000e+00 11 -1.02958785e-02 -0.00000000e+00 +1.94908323e-08 +5.02431273e-08 -7.49601117e-08 -6.04651180e-10 +7.36529066e-10 -1.87661697e-10 

# scuff-neq run on jzh-virtual-machine (01/26/16::19:51:59)
# data file columns: 
# 1 transform tag
# 2 omega 
# 3 (sourceObject,destObject) 
# 4 PAbs flux spectral density
# 5 PRad flux spectral density
# 6 XForce flux spectral density
# 7 YForce flux spectral density
# 8 ZForce flux spectral density
# 9 XTorque flux spectral density
# 10 YTorque flux spectral density
# 11 ZTorque flux spectral density
DEFAULT 1.000000e-01 11 -4.18913321e-06 -0.00000000e+00 +7.59667464e-14 +1.89225711e-13 -2.86156245e-13 -2.83334014e-15 -3.05668447e-16 -1.13905528e-14 
```
Here, PRad flux spectral density is still -0.00000000e+00. Why is it -0.00000000e+00 ?
