### ISSUE TITLE
more Nodes and Elements generated by gmsh version of 2.10.1

### ISSUE THREAD

**Issue by ZhihaoJia16** [HomerReid/scuff-em#80]
I update the version of gmsh from 2.8.3 to 2.10.1.
In examples of Thermal radiation, heat transfer, and non-equilibrium Casimir forces between silicon dioxide spheres, when I run 
```
% gmsh -2 -clscale 0.5 Sphere.geo
% RenameMesh Sphere.msh
```
it does not generate `Sphere_1479.msh`, but `Sphere_1485.msh`. And threre are`498 Nodes and 991 Elements` in  `Sphere_1485.msh`.
I run,
```
% gmsh -2 -clscale 1 Sphere.geo
% RenameMesh Sphere.msh
```
it's ok, generating `Sphere_501.msh`,

When the version of gmsh is 2.8.3, it's ok, genarating `Sphere_501.msh` and `Sphere_1479.msh`. But it‘s still not ok when I remove 2.10.1 gmsh and install 2.8.3 gmsh.

**Comment by HomerReid** [comment]
These are minor discrepancies among various GMSH versions that have absolutely no bearing on the performance of SCUFF-EM, other than to require simple modifications of the example `.scuffgeo` files included in the source distribution to refer to the proper `.msh` files generated by whatever version of GMSH you happen to be running.

**Comment by ZhihaoJia16** [comment]
Thank you for your answer.
