### ISSUE TITLE
basic problems installing 

### ISSUE THREAD

**Issue by jordipratcamps** [HomerReid/scuff-em#87]
Hi all, 

I have had some difficulties installing the software. I apologize for my extremely basic level... I'm pretty lost. At some point, after installing some more packages (apt-get install meep h5utils autoconf) I reached the following point: 

config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure: **
configure: ** The configure process was successful.
configure: ** Now type 'make' to compile and sudo 'make install'.

So everything seemed to work. I typed make and I got: 

../../../../ylwrap: line 176: yacc: command not found
make[4]: *** [parser.c] Error 127
make[4]: Leaving directory `/home/jordi/scuff-em/src/libs/libMatProp/cmatheval'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/home/jordi/scuff-em/src/libs/libMatProp'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/jordi/scuff-em/src/libs'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/jordi/scuff-em/src'
make: *** [install-recursive] Error 1

Same result when I type make install. It seems the program is not installed since I don't see any executable file inside the folder I specified neither the example files....

I would acknowledge very much your help! I'm looking forward to start using the software!!

**Comment by ZhihaoJia16** [comment]
you may try  `sudo apt-get install bison`
reference to these
[https://www.howtoforge.com/community/threads/make-yacc-command-not-found-building-libpcap.9264/](https://www.howtoforge.com/community/threads/make-yacc-command-not-found-building-libpcap.9264/)
 [http://www.linuxquestions.org/questions/linux-software-2/yacc-command-not-found-408747/](http://www.linuxquestions.org/questions/linux-software-2/yacc-command-not-found-408747/)

**Comment by jordipratcamps** [comment]
Thank you very much!!!!
After following your advice and installing bison I had to install "flex" too (sudo apt-get install flex) and finally worked!
:-)
