### ISSUE TITLE
error about --OmegaKPoints (scuff-neq for 1D gratings )

### ISSUE THREAD

**Issue by ZhihaoJia16** [HomerReid/scuff-em#88]
Hi,
I am using `scuff-neq` to compute the **Radiative heat transfer** between 1D SiO2 gratings in the paper [Radiative heat transfer between two dielectric nanogratings in the scattering approach](http://journals.aps.org/prb/abstract/10.1103/PhysRevB.86.085432)
![1](https://cloud.githubusercontent.com/assets/16773876/14634126/298f91d8-0653-11e6-92ff-5f94e7f2902f.jpg)
T1 = 310 K ,T2 = 290 K, d = 1500 nm,  p' = 300 nm, a = 500 nm, δ = 750 nm, L = 100nm.
Here's the files computing this structure.
[Doublegrating.scuffgeo.txt](https://github.com/HomerReid/scuff-em/files/225802/Doublegrating.scuffgeo.txt)
[lowergrating.geo.txt](https://github.com/HomerReid/scuff-em/files/225801/lowergrating.geo.txt)
[lowergrating_253.msh.txt](https://github.com/HomerReid/scuff-em/files/225803/lowergrating_253.msh.txt)
[OKBFile.txt](https://github.com/HomerReid/scuff-em/files/225804/OKBFile.txt)
[RunScript.txt](https://github.com/HomerReid/scuff-em/files/225805/RunScript.txt)
[uppergrating.geo.txt](https://github.com/HomerReid/scuff-em/files/225806/uppergrating.geo.txt)
[uppergrating_253.msh.txt](https://github.com/HomerReid/scuff-em/files/225807/uppergrating_253.msh.txt)

Here's the content of the file `Doublegrating.scuffgeo`
```
LATTICE
       VECTOR 1.5  0.0
       VECTOR 0.0  0.1
ENDLATTICE 

MATERIAL SIO2
  A1              = 8.2736e+13;
  w01             = 8.54484e+13;
  G1              = 8.46448e+12;
  A2              = 1.58004e+14;
  w02             = 2.029e+14;
  G2              = 1.06449e+13;
  A3              = 3.39786e+13;
  w03             = 1.51198e+14;
  G3              = 8.33205e+12;
  EpsInf          = 2.03843;

  Eps(w) = EpsInf + A1*A1/(w01*w01 - w*w - i*w*G1) + A2*A2/(w02*w02 - w*w - i*w*G2) + A3*A3/(w03*w03 - w*w - i*w*G3);
ENDMATERIAL

REGION UpperGrating MATERIAL SIO2
REGION Gap          MATERIAL Vacuum
REGION LowerGrating MATERIAL SIO2

SURFACE UpperGratingSurface
	MESHFILE uppergrating_253.msh
	REGIONS  UpperGrating Gap
	DISPLACED 0 0 1.1
ENDOBJECT

SURFACE LowerGratingSurface
	MESHFILE lowergrating_253.msh
	REGIONS  LowerGrating Gap
ENDOBJECT
```
When I run
``` 
#!/bin/bash
ARGS=""
ARGS="${ARGS} --geometry Doublegrating.scuffgeo"
ARGS="${ARGS} --Temperature UpperGratingSurface 310"
ARGS="${ARGS} --Temperature LowerGratingSurface 290"
ARGS="${ARGS} --Power"

scuff-neq ${ARGS}
```
get error`error: --OmegaKPoints is required for extended geometries (aborting)`.
So, I add `OKBFile` file. 
```
1.33E-002 2.09333 31.4
6.00E-002 2.09333 31.4
1.07E-001 2.09333 31.4
1.53E-001 2.09333 31.4
2.00E-001 2.09333 31.4
2.47E-001 2.09333 31.4
2.93E-001 2.09333 31.4
3.40E-001 2.09333 31.4
3.87E-001 2.09333 31.4
4.33E-001 2.09333 31.4
4.80E-001 2.09333 31.4
5.27E-001 2.09333 31.4
5.73E-001 2.09333 31.4
6.20E-001 2.09333 31.4
6.67E-001 2.09333 31.4
7.13E-001 2.09333 31.4
7.60E-001 2.09333 31.4
8.07E-001 2.09333 31.4
8.53E-001 2.09333 31.4
9.00E-001 2.09333 31.4
9.47E-001 2.09333 31.4
9.93E-001 2.09333 31.4
1.04E+000 2.09333 31.4
1.09E+000 2.09333 31.4
1.13E+000 2.09333 31.4
1.18E+000 2.09333 31.4
1.23E+000 2.09333 31.4
1.27E+000 2.09333 31.4
1.32E+000 2.09333 31.4
```
The first number on each line is the `--Omega` value; the second number is  Bloch wavevector π/1.5 (1.5 is the lattice constant in x-direction); the third number is  Bloch wavevector π/0.1(0.1 is the lattice constant in y-direction).
* Is the content of  `OKBFile` file right?

When I run
```
#!/bin/bash
ARGS=""
ARGS="${ARGS} --geometry Doublegrating.scuffgeo"
ARGS="${ARGS} --OmegaKFile OKBFile"
ARGS="${ARGS} --Temperature UpperGratingSurface 310"
ARGS="${ARGS} --Temperature LowerGratingSurface 290"
ARGS="${ARGS} --Power"

scuff-neq ${ARGS}
```
I get `.SIFlux.EMT` file. 
* I do not know the numerical value Φ  in `.SIFlux.EMT` file is only about kB= (2.09333, 31.4) or the sum of all kB?
* How should I do to get the other two files (`.SIIntegrand`, and `.NEQPFT` files)?

best,
Thank you in advance.

**Comment by HomerReid** [comment]
``scuff-neq`` doesn't support periodic geometries. I am working on that, but it won't be ready for several months.

**Comment by ZhihaoJia16** [comment]
Thank you for your quick reply.
Are there other ways to calculate the radiative heat transfer of the periodic structure by scuff-em or buff-em? Or other codes?

**Comment by HomerReid** [comment]
The only way to do this in SCUFF-EM at present would be to consider finite-size structures and extrapolate to the infinite-size limit. I am not aware of any other numerical code that could handle this structure. 

My rough timeline for having this available in SCUFF-EM would be somewhere around June/July 2016.

**Comment by ZhihaoJia16** [comment]
Thank you for your suggestion. I am trying that. 
And I'm looking forward to update of scuff-neq.
