### ISSUE TITLE
Unit of mesh files

### ISSUE THREAD

**Issue by ww9980** [HomerReid/scuff-em#97]
Hi Homer,

Thanks for making this amazing tool and the detailed documents! Just wonder if the unit of the mesh file matters for the solver? Because I had an impression that the unit was in `um` when I was going through the documents but I was unable to find the source again. Could you please confirm what it is.

Thank you, 
Fan

**Comment by HomerReid** [comment]
Thanks for your interest. The only time the code makes reference to explicit length units is when evaluating frequency-dependent dielectric functions (in which case the default length unit is assumed to be microns, although this is changeable).

If you use no frequency-dependent dielectric functions (that is, if all of your materials are either `PEC` or frequency-independent materials like `CONST_EPS_12.0` or `CONST_EPS_5+6i_MU_10.2`) then there are no explicit length units. In this case, writing a mesh file to describe a structure with typical lengths of `1.0` and running calculations with frequency specification like `--Omega 1.0` will produce results that can be interpreted as describing 

+ a structure with typical lengths of 1 micron and a frequency of 3e14 rad/sec, or

+ a structure with typical lengths of 1 millimeter and a frequency of 3e11 rad/sec, or

+ a structure with typical lengths of 1 meter and a frequency of 3e8 rad/sec

etc.

**Comment by ww9980** [comment]
Thanks for your reply! Just wonder when it's without freq-dependent dielectrics, does it make a difference between a larger structure and a smaller one? Does it consume more computation time given the same mesh structure in different scales?

**Comment by HomerReid** [comment]
Without frequency-dependent dielectrics, the code has no knowledge of the length scale you have in mind, so no results can depend on this. Computations for the same mesh file and same input arguments will be identical in every way regardless of whether you interpret `1.0` as 1 micron or 1 meter.

**Comment by ww9980** [comment]
Thanks, last question: 
in `SCUFF-RF`, when `GHz` is assumed in `--frequency` option, what is the corresponding length unit in a structure?
I understand that `--Omega` is 
$\Omega=c/\lambda$,
so is the unit in `SCUFF-RF` $L=c/f=3m$ by default then?
Thanks.

**Comment by HomerReid** [comment]
No, for SCUFF-RF the default length unit is 1 mm and the default angular frequency unit is $\omega=c/1 mm = 3^{11}$ rad/sec. The `--frequency` option to SCUFF-RF specifies the *linear* (not angular) frequency in units of GHz.

SCUFF-RF is the only application code in the SCUFF-EM suite for which the default length unit differs from 1 micron.

**Comment by ww9980** [comment]
Thanks for your reply, I have fully known the units now. Thanks!
